create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  session_id text not null,
  anonymous_user_id text,
  screen text,
  story_id bigint,
  duration_seconds double precision,
  metadata_json jsonb default '{}'::jsonb,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_event_name_idx
  on public.analytics_events (event_name);

create index if not exists analytics_events_session_id_idx
  on public.analytics_events (session_id);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);
